CREATE SCHEMA IF NOT EXISTS f1_bronze;
CREATE SCHEMA IF NOT EXISTS f1_silver;
CREATE SCHEMA IF NOT EXISTS f1_gold;

GRANT ALL ON SCHEMA f1_bronze TO dagster;
GRANT ALL ON SCHEMA f1_silver TO dagster;
GRANT ALL ON SCHEMA f1_gold TO dagster;