[destination.postgres.credentials]

database = "dagster"
username = "dagster"
password = "dagsterpass" # replace with your password
host = "postgres" # or the IP address location of your database
port = 5432
connect_timeout = 15